<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-0FSTDRC" name="com.freshproposals.selenium.Signature_Duplicate_Proposal" tests="13" failures="2" timestamp="2020-03-21T12:48:51 IST" time="42.500" errors="0">
  <testcase name="login" time="0.711" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="open_Proposal" time="10.395" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="height_width" time="3.516" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="assert_width_1" time="0.102" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="assert_height_1" time="0.088" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="duplicate" time="2.459" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="DragDrop" time="3.478" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="assert_width_2" time="0.107" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal">
    <failure type="java.lang.AssertionError" message="expected [300px] but found [298px]">
      <![CDATA[java.lang.AssertionError: expected [300px] but found [298px]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.freshproposals.selenium.Signature_Duplicate_Proposal.assert_width_2(Signature_Duplicate_Proposal.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$45/1995616381.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- assert_width_2 -->
  <testcase name="assert_height_2" time="0.087" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal">
    <failure type="java.lang.AssertionError" message="expected [125px] but found [84.5938px]">
      <![CDATA[java.lang.AssertionError: expected [125px] but found [84.5938px]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.freshproposals.selenium.Signature_Duplicate_Proposal.assert_height_2(Signature_Duplicate_Proposal.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$45/1995616381.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- assert_height_2 -->
  <testcase name="Save" time="7.303" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="reset_sign_1" time="3.472" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="clear" time="3.574" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
  <testcase name="Save2" time="7.208" classname="com.freshproposals.selenium.Signature_Duplicate_Proposal"/>
</testsuite> <!-- com.freshproposals.selenium.Signature_Duplicate_Proposal -->
