<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-0FSTDRC" name="com.freshproposals.selenium.Analytics_Template_Scratch" tests="7" failures="1" timestamp="2020-04-16T11:27:02 IST" time="282.483" errors="0">
  <testcase name="SetUnmPwd" time="0.638" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
  <testcase name="createTemplate" time="20.936" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
  <testcase name="proposalMethods" time="240.454" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
  <testcase name="Summary" time="11.240" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
  <testcase name="extendsMethods2" time="5.196" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
  <testcase name="Assert_time" time="2.011" classname="com.freshproposals.selenium.Analytics_Template_Scratch">
    <failure type="java.lang.AssertionError" message="expected [3 m 10 s] but found [2 m 13 s]">
      <![CDATA[java.lang.AssertionError: expected [3 m 10 s] but found [2 m 13 s]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.freshproposals.selenium.Analytics_Template_Scratch.Assert_time(Analytics_Template_Scratch.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$45/885851948.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Assert_time -->
  <testcase name="Assert_view" time="2.008" classname="com.freshproposals.selenium.Analytics_Template_Scratch"/>
</testsuite> <!-- com.freshproposals.selenium.Analytics_Template_Scratch -->
